### ISSUE TITLE
reset.css 추가

### ISSUE THREAD

**Issue by daadaadaah** [dev-answer/dev-answer#25]
## Why
- 크로스브라우징을 위해 필요
> 어떤 웹 브라우저에서든 사용자들에게 동일한 화면을 볼 수 있도록 해야 한다.
> 그런데, 브라우저마다 렌더링 엔진이 달라서 태그의 기본 스타일이 다르므로, 동일한 HTML 문서라도 웹 브라우저 마다 다르게 보인다.
> 따라서, 모든 브라우저에서 동일한 화면을 볼 수 있도록 브라우저마다 가지고 있는 태그의 기본 스타일을 제거해줘야 하기 때문에 필요

## How
- [ ] `index.css` 만들어서 index.tsx에서 import 시키기
```css
/* index.css */
html, body, div, span, applet, object, iframe,
h1, h2, h3, h4, h5, h6, p, blockquote, pre,
a, abbr, acronym, address, big, cite, code,
del, dfn, em, img, ins, kbd, q, s, samp,
small, strike, strong, sub, sup, tt, var,
b, u, i, center,
dl, dt, dd, ol, ul, li,
fieldset, form, label, legend,
table, caption, tbody, tfoot, thead, tr, th, td,
article, aside, canvas, details, embed, 
figure, figcaption, footer, header, hgroup, 
menu, nav, output, ruby, section, summary,
time, mark, audio, video {
  margin: 0;
  padding: 0;
  border: 0;
  font-size: 100%;
  font: inherit;
  vertical-align: baseline;
}
article, aside, details, figcaption, figure, 
footer, header, hgroup, menu, nav, section {
  display: block;
}
body {
  line-height: 1;
}
ol, ul {
  list-style: none;
}
blockquote, q {
  quotes: none;
}
blockquote:before, blockquote:after,
q:before, q:after {
  content: '';
  content: none;
}
table {
  border-collapse: collapse;
  border-spacing: 0;
}
```
## Note
- emotion에서 제공하는 reset.css 가 있긴 한대.
- 다른 라이브러리 사용했을 때, 그 라이브러리에서 제공하는 reset.css랑 emotion의 reset.css랑 다르면, 또 그거에 맞춰 수정할 수도 있을 것 같아서, 라이브러리에 의존하지 않고 우리만의 index.css 사용할까 합니다
